# Generate data/espn-crests.json from behind dev.opt's DNS block.
#
# dev.opt refuses DNS for site.api.espn.com, so this resolves the IP over
# DNS-over-HTTPS (Cloudflare 1.1.1.1 is an IP literal — no DNS needed) and
# pins it with curl --resolve (correct SNI + cert, unlike IP fetching).
# The image CDN (a.espncdn.com) resolves via system DNS, no workaround needed.
#
# Usage: powershell -ExecutionPolicy Bypass -File scripts/fetch-espn-crests.ps1
# Mirrors scripts/fetch-espn-crests.mjs (for machines with normal DNS).

$ErrorActionPreference = "Stop"
$OutFile = Join-Path $PSScriptRoot "../data/espn-crests.json"
$Tmp = Join-Path ([System.IO.Path]::GetTempPath()) "opencode"

$Leagues = [ordered]@{
  "premier-league"   = "eng.1"
  "la-liga"          = "esp.1"
  "serie-a"          = "ita.1"
  "bundesliga"       = "ger.1"
  "ligue-1"          = "fra.1"
  "champions-league" = "uefa.champions"
  "europa-league"    = "uefa.europa"
  "conference-league"= "uefa.europa.conf"
  "eredivisie"       = "ned.1"
  "liga-portugal"    = "por.1"
  "championship"     = "eng.2"
}

# Resolve ESPN API IP via DNS-over-HTTPS (IP literal, bypasses local DNS).
$doh = curl.exe -s --max-time 10 -H "Accept: application/dns-json" `
  "https://1.1.1.1/dns-query?name=site.api.espn.com&type=A" | ConvertFrom-Json
$espnIp = ($doh.Answer | Where-Object { $_.type -eq 1 } | Select-Object -First 1).data
if (-not $espnIp) { throw "DoH resolution failed" }
Write-Host "site.api.espn.com -> $espnIp"
$resolveFlag = "site.api.espn.com:443:$espnIp"

$teams = [ordered]@{}
$total = 0
$valid = 0

foreach ($comp in $Leagues.Keys) {
  $slug = $Leagues[$comp]
  Write-Host -NoNewline "$comp ($slug)... "
  try {
    $rawFile = Join-Path $Tmp "espn-$comp.json"
    curl.exe -s --max-time 20 --resolve $resolveFlag `
      "https://site.api.espn.com/apis/site/v2/sports/soccer/$slug/teams" -o $rawFile
    $json = Get-Content -Encoding UTF8 -Raw -LiteralPath $rawFile | ConvertFrom-Json
    $entries = $json.sports[0].leagues[0].teams
    Write-Host -NoNewline "$($entries.Count) teams, validating... "
    $verified = @()
    foreach ($e in $entries) {
      $t = $e.team
      if (-not $t -or -not $t.displayName -or -not $t.id) { continue }
      $total++
      $url = "https://a.espncdn.com/i/teamlogos/soccer/500/$($t.id).png"
      $code = curl.exe -s -o NUL -w "%{http_code}" --max-time 10 $url
      if ($code -eq "200") {
        $valid++
        $verified += [ordered]@{ id = "$($t.id)"; name = "$($t.displayName)"; url = $url }
      }
    }
    $teams[$comp] = $verified
    Write-Host "$($verified.Count) OK"
  } catch {
    Write-Host "FAILED: $($_.Exception.Message)"
    $teams[$comp] = @()
  }
}

$out = [ordered]@{
  generatedAt = (Get-Date).ToUniversalTime().ToString("o")
  note = "Auto-generated by fetch-espn-crests.ps1. $valid/$total URLs validated."
  teams = $teams
}
$json = $out | ConvertTo-Json -Depth 6
# UTF-8 no BOM (matches .mjs output; avoids mojibake in displayNames).
[System.IO.File]::WriteAllText($OutFile, $json + "`n", (New-Object System.Text.UTF8Encoding $false))
Write-Host "`nWrote $OutFile"
Write-Host "$valid/$total URLs valid across $($teams.Count) competitions"
